version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '13000:5432'

  nginx:
    depends_on:
      - api-client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5000:80'

  api-client:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./api-client
    volumes:
      - ./api-client:/app
    restart: always
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres_password
      PGPORT: 5432
    expose:
      - '5000'

  mudbus-listener:
    depends_on:
      - api-client
      - postgres
    #restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./modbus-listener
    volumes:
      - ./modbus-listener:/app
#  web-interface:
#    depends_on:
#      - api-client
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./web-interface
#    volumes:
#      - ./web-interface:/app
#    restart: always
#    environment:
#      APICLIENTURL: api-client
#    expose:
#      - '3000'
