FROM python:3.10-alpine

RUN mkdir /app

WORKDIR /app
RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

ADD ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

ADD . /app

CMD [ "python", "app.py" ]