FROM python:3.10-alpine

RUN mkdir /app

ADD . /app
WORKDIR /app
RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev
RUN pip install -r requirements.txt
CMD [ "python", "app.py" ]